import fs from 'node:fs';
import path from 'node:path';
import { config } from '../config.js';
import { GAME_CATALOG } from '../knowledge/catalog.js';

/**
 * Writes the cycle's outcome as Markdown — the body of the auto-update pull
 * request — so the daily PR says what the agent actually did instead of a
 * fixed two-line stub. Also keeps the raw summary in data/last-cycle.json.
 */
export function writeCycleReport(summary = {}, { reportsDir = config.paths.reports, lastCycleFile = config.paths.lastCycleFile } = {}) {
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });
  const md = renderCycleReport(summary);
  const mdPath = path.join(reportsDir, 'latest.md');
  fs.writeFileSync(mdPath, md);
  fs.writeFileSync(lastCycleFile, JSON.stringify(summary, null, 2));
  return mdPath;
}

const name = id => GAME_CATALOG[id]?.name || id;
const pct = n => (n == null ? '—' : `${n}%`);

export function renderCycleReport(s = {}) {
  const a = s.actions || {};
  const lines = [];
  lines.push(`## Marketing agent — ${s.action || 'cycle'} · ${(s.timestamp || new Date().toISOString()).slice(0, 16).replace('T', ' ')} UTC · **${(s.mode || 'draft').toUpperCase()}**`);
  lines.push('');

  // Organic queue
  lines.push('### Content queue');
  lines.push(`- Planned: **${a.plannedPosts ?? 0}** new item(s) · Published this run: **${a.publishedPosts ?? 0}** (${s.mode === 'live' ? 'live' : 'draft — simulated, nothing went out'})`);
  if (a.scoutedLeads != null) lines.push(`- Scout: **${a.scoutedLeads}** community lead(s) evaluated, replies drafted for review`);
  if (a.generatedCards != null) lines.push(`- Visual cards refreshed: **${a.generatedCards}**`);
  lines.push('');

  // Play-together video
  lines.push('### Play-together video');
  const v = a.togetherVideo;
  if (v?.gameId) {
    lines.push(`- **${name(v.gameId)}** — ${v.mode === 'live' ? `posted: ${v.url || v.postId}` : 'drafted (not posted)'}${v.renderSeconds ? ` · ${v.renderSeconds}s of footage` : ''}`);
    if (v.videoFile) lines.push(`- File: \`${v.videoFile}\` (+ square variant) — attached to this workflow run as an artifact; not committed`);
    if (v.text) lines.push(`- Copy: > ${v.text}`);
  } else if (v?.skipped) {
    lines.push(`- Skipped: ${v.skipped}`);
  } else {
    lines.push('- Not due this run');
  }
  lines.push('');

  // Ads
  lines.push('### X Ads');
  const ads = a.ads;
  if (!ads) {
    lines.push('- Not enabled (set `X_ADS_ACCOUNT_ID`)');
  } else {
    if (ads.blocked) lines.push(`- ⏳ **Blocked:** ${ads.blocked}`);
    lines.push(`- Reviewed **${ads.reviewed ?? 0}** active campaign(s), paused **${ads.paused ?? 0}**, ${ads.launched ? '**launched 1**' : 'launched none'}${ads.plannedBrief ? ` — next brief: ${name(ads.plannedBrief.gameId)} / ${ads.plannedBrief.angle}${ads.plannedBrief.videoPath ? ' (video creative)' : ''}` : ''}`);
    if (ads.committedDailyUsd != null) lines.push(`- Committed spend: **$${ads.committedDailyUsd}/day** of the $${ads.policy?.maxTotalDailyUsd ?? 25}/day cap (≤ $${ads.policy?.maxDailyPerCampaignUsd ?? 10}/day per campaign, ${ads.policy?.trialDays ?? 2}-day trial)`);
    if (ads.preflight) {
      const p = ads.preflight;
      lines.push(`- Preflight: ${p.checks.map(c => `${c.ok ? '✅' : '⚠️'} ${c.label}`).join(' · ')}`);
    }
  }
  lines.push('');

  // Organic metrics
  lines.push('### Organic performance (our own tweets)');
  const m = a.metrics;
  const games = m?.summary ? Object.entries(m.summary) : [];
  if (games.length) {
    lines.push('| Game | Posts | Impressions | Link clicks | CTR | Engagement |');
    lines.push('|---|---:|---:|---:|---:|---:|');
    for (const [id, g] of games.slice(0, 8)) lines.push(`| ${name(id)}${g.videoPosts ? ` (${g.videoPosts} video)` : ''} | ${g.posts} | ${g.impressions} | ${g.linkClicks} | ${pct(g.ctrPercent)} | ${pct(g.engagementPercent)} |`);
  } else {
    lines.push(`- ${m?.note || 'No live tweets measured yet — metrics start once posts go out in live mode.'}`);
  }
  lines.push('');

  if (Array.isArray(s.nextSteps) && s.nextSteps.length) {
    lines.push('### Next steps');
    for (const n of s.nextSteps) lines.push(`- ${n}`);
    lines.push('');
  }

  lines.push('_Generated by the marketing agent. Videos are workflow-run artifacts; data and reports are committed._');
  return lines.join('\n');
}
